# Google credentials are tied to berkeley.edu account (and client ID GabbleGrid)

credentials:
  google:
    client_id: 963767332426-hpgnd37oq1qhvri54o6f2qfj9ppfmfib.apps.googleusercontent.com
    client_secret: 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
  github:
    client_id: Ov23liyqWopVe0STp8SV
    client_secret: fec7943bc248bc7c6d53dba0dd557c5a4e8751ab
    redirect_uri: https://gabblegrid.com
